#!/usr/bin/env python3

import random
import argparse

# list of words, numbers, symbols
wordlist = open('Desktop/words.txt', 'r')
readwords = wordlist.read()
listedwords = readwords.split('\n')
listednums = ['1','2','3','4','5','6','7','8','9','0']
listedsymbols = ['~','!','@','#','$','%','^','&','*','.',':',';']

parser = argparse.ArgumentParser(
        prog='Password Generator',
        description='Generate a secure, memorable password using the XKCD method')
parser.add_argument('-w','--words', metavar='WORDS', type=int, default=4, required=False, help='include WORDS words in the password (default=4)')
parser.add_argument('-c','--caps', metavar='CAPS', type=int, default=0, required=False, help='capitalize the first letter of CAPS random words (default=0)')
parser.add_argument('-n','--numbers', metavar='NUMBERS', type=int, default=0, required=False, help='insert NUMBERS random numbers in the password (default=0)')
parser.add_argument('-s','--symbols', metavar='SYMBOLS', type=int, default=0, required=False, help='insert SYMBOLS random symbols in the password (default=0)')
args = parser.parse_args()
words = args.words
caps = args.caps
numbers = args.numbers
symbols = args.symbols 

# add capitalized words
password = [i.title() for i in random.sample(listedwords,caps)]

# add rest of words
restwords = words - caps
password += random.sample(listedwords,restwords)

# add random numbers
password += random.sample(listednums,numbers)

# add random symbols
password += random.sample(listedsymbols,symbols)

# shuffle password
random.shuffle(password)
print(''.join(password))

